### ISSUE TITLE
Add "What's New" section

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/thunderbird-website#120] opened 2019-08-26 05:06 UTC
As per @ryanleesipes request, I'm creating a **What's New** page in the new website that will be used to highlight specific features of the new version.
This is the content Ryan created on SUMO: https://support.mozilla.org/en-US/kb/new-thunderbird-68

How should we handle it on our end?
Should we extend the release notes and introduce a new `tag`, maybe highlights, in order for me to fetch it and filter it out for this new page?
Should we create a completed separated YAML file, with screenshots stored here on GitHub in version related folders?

I already updated the `builder.py` for the new website in order to create version specific `what's new` pages, now I need to content to pull from somewhere.

What do you guys think?

**Comment by mkmelin** [comment] 2019-08-26 19:04
I think it's fine to have it go to sumo until we get this one set up.

**Comment by MadMattAu** [comment] 2019-10-25 10:01
So we can abandon update to the Sumo page I assume.  That will please me as finding out what has changed is a big job.  I stopped doing it after 60 as translating change from release notes to actual bug to get details is more work that I am interested in.

Some statistics that are relevant to this what is new thing.  Visits to various SUMO pages over the last 90 days would suggest care is required in informing folk what is new.  Many are NOT using the current version. As these figures show "What is new" in 60, 52 and 45 make up 3 of the 4 most visited pages.  68 is sitting down there with about 3 thousand views.  That might change with updates being turned on,  We will see, but as the update more info link goes to the release notes I have my doubts.


Article | Visits | Status | Needs Update | Ready for L10N | Stale | Expiry Date
-- | -- | -- | -- | -- | -- | --
New in Thunderbird 60 | 233,310 | Live |   | Yes |   |   | Show translations
Filelink for Large Attachments | 35,271 | Live |   | Yes |   |   | Show translations
New in Thunderbird 52.0 | 31,039 | Review Needed: add obsolete version notice |   | Yes |   |   | Show translations
New in Thunderbird 45.0 | 25,849 | Live |   | Yes |   |   | Show translations
Get community support | 22,305 | Live |   | Yes |   |   | Show translations
Moving Thunderbird Data to a New Computer | 16,033 | Live |   | Yes |   |   | Show translations
Profiles - Where Thunderbird stores your messages and other user data | 14,475 | Live |   | Yes |   |   | Show translations
Unable to install add-ons (extensions or themes) in Thunderbird | 11,287 | Live |   | Yes |   |   | Show translations
New in Thunderbird 38.0 | 9,961 | Live |   | Yes |   |   | Show translations
Ignoring threads | 9,810 | Live |   | Yes |   |   | Show translations
Thunderbird and Gmail | 8,644 | Live |   | Yes |   |   | Show translations
Signatures | 6,202 | Live |   | Yes |   |   | Show translations
Manual Account Configuration | 5,660 | Live |   | Yes |   |   | Show translations
Updating Thunderbird | 5,393 | Live |   | Yes |   |   | Show translations
Using Lightning with Google Calendar | 5,388 | Live |   | Yes |   |   | Show translations
Cannot send messages | 4,774 | Live |   | Yes |   |   | Show translations
Switching to Thunderbird | 4,755 | Live |   | Yes |   |   | Show translations
Remote Content in Messages | 4,749 | Live |   | Yes |   |   | Show translations
Password Manager - Remember, delete and change passwords in Thunderbird | 4,701 | Live |   | Yes |   |   | Show translations
Using Multiple Profiles | 4,490 | Live |   | Yes |   |   | Show translations
Installing Thunderbird on Windows | 4,382 | Live |   | Yes |   |   | Show translations
Installing Thunderbird on Linux | 4,160 | Live |   | Yes |   |   | Show translations
New in Thunderbird 68.0 | 3,855 | Live |   | Yes |   |   | Show translations
Cannot receive messages | 3,656 | Live |   | Yes |   |   | Show translations
Installing Thunderbird on Mac | 3,617 | Live |   | Yes |   |   | Show translations
Keyboard Shortcuts TB | 3,397 | Live |   | Yes |   |   | Show translations
Switch from POP to IMAP account | 3,332 | Live |   | Yes |   |   | Show translations
Automatic Account Configuration | 3,232 | Live |   | Yes |   |   | Show translations
Digitally Signing and Encrypting Messages | 2,912 | Live |   | Yes |   |   | Show translations
How to create and use mailing lists on Thunderbird | 2,806 | Live |   | Yes |   |   | Show translations
Thunderbird and Junk / Spam Messages | 2,801 | Live |   | Yes |   |   | Show translations
Calendar updates issues with Thunderbird | 2,732 | Live |   | Yes |   |   | Show translations
Organize Your Messages by Using Filters | 2,700 | Live |   | Yes |   |   | Show translations
Archived Messages | 2,588 | Live |   | Yes |   |   | Show translations
Display the Thunderbird menus and toolbar | 2,520 | Live |   | Yes |   |   | Show translations
Blocking a sender | 2,389 | Live |   | Yes |   |   | Show translations
IMAP Synchronization | 2,365 | Live |   | Yes |   |   | Show translations
How to Install and Use another Language in the Dictionary on Thunderbird | 2,360 | Live |   | Yes |   |   | Show translations
Install themes to change the look of Thunderbird | 2,260 | Live |   | Yes |   |   | Show translations
Message threading in Thunderbird - keep messages grouped by conversation | 2,131 | Live |   | No |   |   | Show translations
What is the winmail.dat attachment? | 2,095 | Live | Link to MS Support Bulletin/Article discussion:  https://support.mozilla.org/en-US/kb/what-winmaildat-attachment/discuss/7793  - cilias [2018-11-28] | Yes |   |   | Show translations
Sending and Receiving Messages on Thunderbird | 1,987 | Live |   | Yes |   |   | Show translations
Installing an Add-on in Thunderbird | 1,974 | Live |   | Yes |   |   | Show translations
Thunderbird add-ons - frequently asked questions | 1,838 | Live |   | Yes |   |   | Show translations
How to change the Thunderbird layout | 1,570 | Live |   | Yes |   |   | Show translations
New Email Address | 1,570 | Live |   | Yes |   |   | Show translations
Configuration Options for Accounts | 1,516 | Live | needs documentation for NNTP, Chat, and SMTP - CI 2018-02-01 | Yes |   |   | Show translations
Compacting folders | 1,458 | Live |   | Yes |   |   | Show translations
What is the Mozilla Maintenance Service? | 1,385 | Live | [Fx68?] new Update service to replace MMS - see discussion | Yes |   |   | Show translations
unable launch older version on profile | 1,380 | Live | should we mention --allow-downgrade here, or in a separate article? | No |   |   | Show translations
Hyperlinks in Messages Not Working | 1,288 | Live |   | Yes |   |   | Show translations
Make Thunderbird the Default Mail Client | 1,270 | Live |   | Yes |   |   | Show translations
Thunderbird and Hotmail | 1,189 | Live |   | Yes |   |   | Show translations
How to Subscribe to News Feeds and Blogs | 1,187 | Live |   | Yes |   |   | Show translations
How do I create a screenshot of my problem? | 1,139 | Review Needed: Corrected some grammar and added a note detailing  how to take a screenshot on phones running stock Android 9 (Pie). |   | Yes |   |   | Show translations
Rebuilding the Global Database | 1,132 | Live |   | Yes |   |   | Show translations
Config Editor | 1,100 | Live | Screenshot update - Warning now says "I accept the risk". -cilias [2018-11-26] | Yes |   |   | Show translations
Configuration Options for Attachments | 1,010 | Live |   | Yes |   |   | Show translations
Safe Mode Thunderbird | 990 | Live |   | Yes |   |   | Show translations
Vacation Response | 976 | Live |   | Yes |   |   | Show translations
Thunderbird and Yahoo | 964 | Live |   | Yes |   |   | Show translations
Thunderbird FAQ | 895 | Live |   | Yes |   |   | Show translations
Switching the folder pane view | 873 | Live |   | Yes |   |   | Show translations
Keyboard Shortcuts for Searching | 862 | Live |   | Yes |   |   | Show translations
How to Use Attachments | 833 | Live |   | Yes |   |   | Show translations
The difference between IMAP and POP3 | 806 | Review Needed: POP3 you can choose to leave messages on server |   | Yes |   |   | Show translations
Exporting and sharing a calendar | 800 | Live |   | Yes |   |   | Show translations
How can I send a large attachment? | 785 | Live |   | Yes |   |   | Show translations
Configuring Lightning | 777 | Live |   | Yes |   |   | Show translations
Instant Messaging and Chat | 754 | Live | Facebook chat doesn't work anymore, see https://bugzilla.mozilla.org/show_bug.cgi?id=1236133  Further image edits are required to replace images that show Facebook. | Yes |   |   | Show translations
Cannot delete messages | 746 | Live |   | Yes |   |   | Show translations
Message Tags - Categorize your email in Thunderbird | 739 | Live | Needs Linux screenshots - CI 2016-07-18 | Yes |   |   | Show translations
Message List Columns | 734 | Live |   | Yes |   |   | Show translations
How to Customize Toolbars | 718 | Live |   | Yes |   |   | Show translations
Addressing an Email | 712 | Live |   | Yes |   |   | Show translations
Global Search | 708 | Live |   | Yes |   |   | Show translations
Protect your Thunderbird passwords with a Master Password | 703 | Review Needed: clarify that master password does not protect messages |   | Yes |   |   | Show translations
FAQ Changing IMAP to POP | 687 | Live |   | Yes |   |   | Show translations
Avoid and report Mozilla tech support scams | 659 | Live |   | Yes |   |   | Show translations
Creating New Calendars | 657 | Review Needed: clarify starting point for creating a new calendar |   | Yes |   |   | Show translations
Thunderbird Software Update Failed | 628 | Live |   | Yes |   |   | Show translations
Quick Filter Toolbar | 620 | Live |   | Yes |   |   | Show translations
Find what version of Thunderbird you are using | 597 | Live |   | Yes |   |   | Show translations
Maildir in Thunderbird | 582 | Live |   | Yes |   |   | Show translations
Uninstall Thunderbird from your computer | 571 | Live |   | Yes |   |   | Show translations
Advanced panel - System, network, updates, and other advanced settings in Thunderbird | 563 | Live |   | Yes |   |   | Show translations
How can I get the latest version of Thunderbird on Windows XP or Vista? | 549 | Live |   | Yes |   |   | Show translations
How to use a Virtual Card (vCard) | 545 | Live | Needs new screenshots for linux. | Yes |   |   | Show translations
How to disable or change the Thunderbird start page | 541 | Live |   | Yes |   |   | Show translations
Changing calendar preferences | 506 | Live |   | Yes |   |   | Show translations
Changing IMAP to POP | 497 | Live |   | Yes |   |   | Show translations
Lightning User Interface | 482 | Live |   | Yes |   |   | Show translations
How to Customize the New Mail Sound | 468 | Live |   | Yes |   |   | Show translations
Creating a new event or task | 464 | Live |   | Yes |   |   | Show translations
Thunderbird support has ended for Mac OS X 10.6, 10.7 and 10.8 | 435 | Live |   | Yes |   |   | Show translations
Thunderbird end of Support for XP and Vista | 416 | Live |   | Yes |   |   | Show translations
Unify your POP email accounts with a global inbox | 411 | Live | Needs Windows and Linux screenshots - CI [2018-07-20] | Yes |   |   | Show translations
Tables - Format messages with rows and columns | 406 | Live |   | Yes |   |   | Show translations
Security panel - Junk, scam, antivirus, and password settings in Thunderbird | 387 | Live |   | Yes |   |   | Show translations
Using Identities | 372 | Live |   | Yes |   |   | Show translations
Adding a holiday calendar | 363 | Live |   | Yes |   |   | Show translations
Thunderbird’s Scam Detection | 332 | Review Needed: http://www.mozilla.org/en-US/firefox/phishing-protection/ link update |   | Yes |   |   | Show translations
Inviting Other People to Events | 307 | Live |   | Yes |   |   | Show translations
Glossary of Terms including types of Accounts | 304 | Live |   | Yes |   |   | Show translations
Open Search | 302 | Live |   | Yes |   |   | Show translations
Names but no Email Addresses are Displayed | 301 | Live |   | Yes |   |   | Show translations
Thunderbird Crashes | 286 | Live |   | Yes |   |   | Show translations
Creating a Newsgroup Account | 251 | Live |   | Yes |   |   | Show translations
Thunderbird and Logjam | 249 | Live |   | Yes |   |   | Show translations
Privacy panel - Remote content and cookie settings in Thunderbird | 235 | Live |   | Yes |   |   | Show translations
Getting started with the Thunderbird main window | 231 | Review Needed: Chris' article is pretty much complete - I've made minor changes |   | Yes |   |   | Show translations
Enable email invitations for CalDAV servers configured to do serverside scheduling | 223 | Live |   | Yes |   |   | Show translations
Mozilla Crash Reporter TB | 199 | Live |   | Yes |   |   | Show translations
Using Saved Searches | 198 | Live |   | Yes |   |   | Show translations
Thunderbird Beta | 186 | Live |   | No |   |   | Show translations
Thunderbird and Comcast | 183 | Live |   | Yes |   |   | Show translations
Thunderbird Accessibility Features | 159 | Live |   | Yes |   |   | Show translations
Changing the Date or Time of an Event | 132 | Live |   | Yes |   |   | Show translations
Thunderbird makes unrequested connections | 132 | Live |   | Yes |   |   | Show translations
Thunderbird and AT&T | 128 | Live |   | Yes |   |   | Show translations
Working with events | 115 | Live |   | Yes |   |   | Show translations
Add Search Engine to Open Search | 94 | Live | Doesn't work on Thunderbird 60 | Yes |   |   | Show translations
Creating a recurring event | 82 | Live |   | Yes |   |   | Show translations
Thunderbird and Sympatico | 53 | Live |   | Yes |   |   | Show translations
Your hardware is no longer supported by Thunderbird | 52 | Live |   | Yes |   |   | Show translations
Configuration Options for Identity | 48 | Live |   | Yes |   |   | Show translations
Forum Response - Asking for Troubleshooting Information (Thunderbird) | 46 | Review Needed: questionS, clarify Pastebin steps, more small edits, use (unused) summary similar to other templates |   | Yes |   |   | Show translations
Dangerous directories |   | Review Needed: Create document for Bug 921410 |   | No |   |   | Show translations
Formatting problems caused by 8bit MIME |   | Review Needed: copy and paste content of wiki only.  Not ready for prome time. |   | No |   |   | Show translations

**Comment by MadMattAu** [comment] 2019-10-26 05:20
![image](https://user-images.githubusercontent.com/5334203/67614403-fe817c80-f803-11e9-95bf-d2709c3a62ac.png)

Perhaps something in the application like Firefox are doing might be more appropriate.

**Comment by mkmelin** [comment] 2019-10-28 19:56
First time someone runs as 68.something they are sent to the what's new page.
That's soon *a lot* of people.

**Comment by ryanleesipes** [comment] 2019-11-12 04:32
Forgot to comment here, but pull request #130 finished the What's New page. Ready for the website to go live and we can point at that page.

See it here: https://www-new.thunderbird.net/en-US/thunderbird/68.0/whatsnew/

**Comment by ryanleesipes** [comment] 2019-11-12 04:33
This was merged 17 days ago btw.

**Closed by ryanleesipes** 2019-11-12 04:32 UTC
