### ISSUE TITLE
Add Windows 64-bit version download link to https://www.thunderbird.net/thunderbird/beta/all/

### ISSUE THREAD

**Issue by ovari** [thundernest/thunderbird-website#49] opened 2018-07-07 03:39 UTC
Please update the "[Download _Thunderbird_ Beta in your language](https://www.thunderbird.net/thunderbird/beta/all/)" page to include the Windows 64-bit build of Thunderbird as it is already available for the [Thunderbird 60.0b9 release](https://ftp.mozilla.org/pub/thunderbird/releases/60.0b9/win64/).
![Download Beta in your language](https://user-images.githubusercontent.com/17465872/42406391-f8d78c84-81e9-11e8-95f5-8c1a253ad924.png)

Perhaps the layout could be similar to the "[Download Firefox in your language](https://www.mozilla.org/firefox/all/)" page.
![Download Firefox in your language](https://user-images.githubusercontent.com/17465872/42406385-d5d02f2a-81e9-11e8-9286-a05d87f1c64c.png)

Thank you

**Comment by ovari** [comment] 2018-07-07 04:50
> b) it is not yet part of our release testing regime (please volunteer to be part of the testing team)

Would showing Thunderbird 64-bit for Windows in the **beta** downloads, not the stable downloads, as suggested in this issue help?

There seems to be testers of win64 already as shown in the comments section of "[Thunderbird 60: extension and theme changes](https://www.ghacks.net/2018/07/06/thunderbird-60-extension-and-theme-changes/)".

> (I'm actually surprised it hasn't come up in tb-planning)

Perhaps it has not come up in tb-planning due the list being moderated?

**Comment by Aris-t2** [comment] 2018-07-07 13:09
@wsmwk 
None of the tests confirm the "send-to" bug still being an issue ( https://bugzilla.mozilla.org/show_bug.cgi?id=393302 ).

**Test environment:**
Win10-1803 64Bit + Thunderbird 60beta9/10 64Bit

_Note:_
Thunderbird is set as default mail client within Windows settings.

**Test cases:**
Send-to works as expected without issues from Word documents, pdf files, websites (all tested browser like Firefox, Edge, Chrome...) and Firefox browsers "Email link..." from location bar.

**Conclusion:**
So, if "a)" is fixed, nothing stops "b)" from progressing and "c)" will be solved automatically.

> a) https://bugzilla.mozilla.org/show_bug.cgi?id=393302 (which blocks tracking bug 634233), b) it is not yet part of our release testing regime (please volunteer to be part of the testing team), c) we are focused in getting version 60 out the door.

**Comment by wsmwk** [comment] 2018-07-07 14:06
Perhaps. But until the bug is closed and confirmed to be settled it is a 
blocker.  The place to explore that is in the bug report.

**Comment by wsmwk** [comment] 2018-07-07 14:08
On 7/7/2018 12:50 AM, ovari wrote:
>
>     (I'm actually surprised it hasn't come up in tb-planning)
>
> Perhaps it has not come up in tb-planning due the list being moderated?
>
Moderation is not a barrier to participation.

But my observation is only that. And the place for action is actually in 
the bug report.

**Comment by Sancus** [comment] 2018-07-07 18:00
Just to set expectations, there won't be any changes made to the website until release drivers confirm that they want the 64-bit version distributed. wsmwk has stated what needs to happen for that above.

This is also low priority due to the TB60 and addons site work happening currently, so I wouldn't expect this to be resolved for some time, but I'm fine with leaving this issue open until it's resolved, since those are some reasonable suggestions about how we should include the builds on the all betas page.

**Comment by ovari** [comment] 2019-03-04 02:01
Bug 393302 Can't "send-to" (MAPI) using Seamonkey and Thunderbird X86_64-bit
https://bugzilla.mozilla.org/show_bug.cgi?id=393302
Status RESOLVED FIXED in Thunderbird 66.0

@Sancus @wsmwk can Thunderbird 66.0b2 release 
https://ftp.mozilla.org/pub/thunderbird/releases/66.0b2/win64/
please be added to
https://www.thunderbird.net/thunderbird/beta/all/

Thank you

**Comment by mkmelin** [comment] 2019-03-04 10:09
64 bit is not yet officially supported. We hope to get there by 68 but there are still some issues, like bug 1509918.

**Comment by nostromov** [comment] 2019-07-10 23:31
For the love of God, where is the 64-bit **ESR** Thunderbird (Is it not being built)? Like Firefox has got: `https://www.mozilla.org/en-US/firefox/organizations/all/`

... Been browsing the FTP, only to find:

`https://ftp.mozilla.org/pub/thunderbird/releases/17.0esr/
https://ftp.mozilla.org/pub/thunderbird/releases/17.0.9esr/

https://ftp.mozilla.org/pub/thunderbird/tinderbox-builds/comm-esr52-win32/
https://ftp.mozilla.org/pub/thunderbird/nightly/latest-comm-esr52-l10n/

https://ftp.mozilla.org/pub/thunderbird/nightly/latest-comm-esr52/`
:(

**Comment by ovari** [comment] 2019-07-11 00:40
@nostromov if your language is `en-US`:
1. Thunderbird 68.0 ESR Beta4 64-bit release for Windows:
https://ftp.mozilla.org/pub/thunderbird/releases/68.0b4/win64/en-US/Thunderbird%20Setup%2068.0b4.exe
https://ftp.mozilla.org/pub/thunderbird/releases/68.0b4/win64/en-US/Thunderbird%20Setup%2068.0b4.msi
2. Thunderbird 70.0 Alpha1 64-bit release for Windows:
https://ftp.mozilla.org/pub/thunderbird/nightly/2019/07/2019-07-10-11-54-19-comm-central/thunderbird-70.0a1.en-US.win64.installer.exe
https://ftp.mozilla.org/pub/thunderbird/nightly/2019/07/2019-07-10-11-54-19-comm-central/thunderbird-70.0a1.en-US.win64.installer.msi

If you advise your preferred language(s), we can advise the link.

Hope this helps

**Comment by mkmelin** [comment] 2019-08-07 10:14
@Sancus, per the discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=634233, I think we want to add 64 bit to the webpage now.

**Comment by Sancus** [comment] 2019-09-07 20:19
64-bit is now live on the website, both via primary download buttons, and "Systems and Languages" page. The layout of that table is a little cramped now, this will be resolved in the redesign.

**Closed by Sancus** 2019-09-07 20:19 UTC
Labels: enhancement

**Comment by ovari** [comment] 2019-09-07 20:52
1. Should the icons be updated from:
a) `Windows` to `Windows 32`?
b) `Linux` to `Linux 32`?
1. Should the headings be updated from:
a) `Windows` to `Windows 32`?
b) `Linux` to `Linux 32`?

**Comment by Sancus** [comment] 2019-09-09 18:42
1. No, icons are going away [in the redesign](https://www-new.thunderbird.net/en-US/thunderbird/all/).
2. I've changed these strings.

**Comment by ovari** [comment] 2019-09-09 22:02
1. Thank you for the link to the redesign.
1. Will the `Windows 64-bit` and `Windows MSI 64-bit` buttons be added to [the redesign](https://www-new.thunderbird.net/en-US/thunderbird/all/)?
1. Will there be a `Recommended` grouping like [Firefox](https://user-images.githubusercontent.com/17465872/42406385-d5d02f2a-81e9-11e8-9286-a05d87f1c64c.png)?

Thank you
