### ISSUE TITLE
"What’s New" link on https://www.thunderbird.net/channel/

### ISSUE THREAD

**Issue by ovari** [thundernest/thunderbird-website#51] opened 2018-07-11 10:29 UTC
Broken link:
https://www.thunderbird.net/thunderbird/60.0beta0/releasenotes/

Link above seems to have a zero '0' after beta that need removing as:
https://www.thunderbird.net/thunderbird/60.0beta/releasenotes/
works.

The installer for TB60 seems to be considerably smaller than TB52. Is the new build system much better and/or is there some other reason?

Thank you

**Comment by wsmwk** [comment] 2018-07-11 10:38
On 7/11/2018 6:29 AM, ovari wrote:
>
> Broken link:
> https://www.thunderbird.net/thunderbird/60.0beta0/releasenotes/
>
I can confirm this


> The installer for TB60 seems to be considerably smaller than TB52. Is 
> the new build system much better and/or is there some other reason?

Different compression makes it smaller.

**Comment by Sancus** [comment] 2018-07-11 20:18
Thanks for the report. This was caused by a regexp that assumed we wouldn't have more than 9 betas 🤣 

Fixed on https://www.thunderbird.net/en-US/channel/ - I purged cache for the major languages(en-US, de, fr, es-ES, ja), rest will update when the Cloudflare cache rolls over in ~8 hours.

**Closed by Sancus** 2018-07-11 20:18 UTC
