### ISSUE TITLE
Supernova website looks messy on mobile

### ISSUE THREAD

**Issue by KyaBamba** [thundernest/thunderbird-website#464] opened 2023-07-11 20:24 UTC
The new website https://www.thunderbird.net/en-US/ looks great on mobile, but the download section gets squeezed pretty badly. 
![download](https://github.com/thundernest/thunderbird-website/assets/73521549/b05a4a4b-8ab8-4444-bbfe-242ec6f22740)

Also in the German version the _tagline_ and _cta-heading_ texts are running too wide and leave the viewport.
![font](https://github.com/thundernest/thunderbird-website/assets/73521549/1dd7de01-d94d-4e96-b54d-86e150e6c0f9)

**Comment by Sancus** [comment] 2023-07-14 16:48
Fixed in https://github.com/thundernest/thunderbird-website/commit/1b9d6ba5e66a39e07b880d1d2e46261a714bc25a

**Closed by Sancus** 2023-07-14 16:48 UTC

**Comment by cadeyrn** [comment] 2023-07-14 16:53
@Sancus As far as I can see https://github.com/thundernest/thunderbird-website/commit/1b9d6ba5e66a39e07b880d1d2e46261a714bc25a only fixes the buttons but not the too large font / horizontal scrolling of the whole website that is caused by this.
