### ISSUE TITLE
Support for small screen devices

### ISSUE THREAD

**Issue by jobisoft** [thundernest/thunderbird-website#142] opened 2019-11-19 08:43 UTC
The new page looks great on large screen devices, but there is no fallback for small screen devices (i tested with iPhone 5). The text and some buttons overlays themself and cannot be read.

I do not know if it is worth the work, just wanted to report my findings.

**Comment by Sancus** [comment] 2019-11-19 18:05
Could you post a screenshot?

This is probably wontfix since you can't download Thunderbird on mobile devices anyways, and the iPhone 5 is quite old. However, I wonder if this may be general mobile Safari bugs or something. The page looks fine on the oldest Android device I have, a Nexus 5(2013). Granted, the iphone 5 screen really is comically small.

![image](https://user-images.githubusercontent.com/479671/69173097-f7245a80-0ab3-11ea-8ce8-7a58fcb07766.png)

**Comment by Alecaddd** [comment] 2019-11-19 18:06
I was going to ask the same question and you beat me by a few minutes :smile:

**Comment by jobisoft** [comment] 2019-11-19 18:35
Here you go. I did not know, if it was a CSS error, or an iPhone error. There is of course no need to fix it for the iPhone.

For some reasons I see german and english text...

![grafik](https://user-images.githubusercontent.com/5830621/69175121-7725e100-0b03-11ea-8ab3-665f166a37fe.png)

**Comment by Alecaddd** [comment] 2019-11-19 18:49
Ah, I see.
That's a webkit issue of the older version of Safari not fully supporting flexbox.
It's a 6 years old issue that has been fixed since version 7 of safari for iOS, released in 2014.
Do we care about fixing this?
I'm OK with a wontfix.

**Comment by jobisoft** [comment] 2019-11-19 18:52
Hm, I am running iOS 10.3.4 on a MD298B/A.

**Comment by Sancus** [comment] 2019-11-19 19:10
I don't know anything about old device support for iOS, do they keep the browsers up to date in addition to security patching the old OS version? Check the Safari version specifically I guess.

If this is correctly an old Safari issue, then no we don't care about fixing this.

**Comment by jobisoft** [comment] 2019-11-19 19:16
I checked with whatismybrowser.com and it tells me I have Safari 10.

I just added that info, because you referred to an issue which has been fixed in safari 7. So that is not the cause for what I am seeing.

I am fine with wontfixing this, just wanted to let you know.

**Comment by Alecaddd** [comment] 2019-11-19 23:38
Let's keep this open for now, I'll see if I can reproduce this issue on my wife's iPhone 6s.
I'll keep you guys posted.

**Comment by Sancus** [comment] 2020-01-31 01:22
@Alecaddd did you ever try to reproduce this or should I just close it?

**Comment by Alecaddd** [comment] 2020-01-31 19:51
Ah, I forgot about this.
I tested it on my wife's iPhone and it looks good.
Let's close this.

**Closed by Alecaddd** 2020-01-31 19:51 UTC
